# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres:9.6
    container_name: postgres-misis
    environment:
      POSTGRES_PASSWORD: 1111
    ports:
      - 5433:5432

  bbq:
    image: misis-bbq
    container_name: misis-bbq
    build:
      dockerfile: ./docker/Dockerfile
      context: ../
    environment:
      PGHOST: postgres-misis
      PGPORT: 5432
    ports:
      - 8080:8080