
###
POST http://localhost:8080/item
Content-Type: application/json

{
  "name": "Маргарита",
  "description": "Помидоры, сыр, лук, орегано",
  "price": 619.0,
  "category": "Пицца",
  "routeStages": [
    {
      "name": "Раскатать тесто в соответствием с размером",
      "duration": 60,
      "products": [
        {"name":  "дрожжевого теста ", "amount":  235},
        {"name":  "мука пшеничная", "amount":  75}
      ]
    },
    {
      "name": "смазать маслом",
      "duration": 10,
      "products": [
        {"name":  "оливковое масло", "amount":  40}
      ]
    },
    {
      "name": "положить слой мелко нарезанных очищенных помидоров",
      "duration": 60,
      "products": [
        {"name":  "помидоры", "amount":  25}
      ]
    },
    {
      "name": "посолить",
      "duration": 5,
      "products": [
        {"name":  "соль", "amount":  2}
      ]
    },
    {
      "name": "сверху покрыть нарезанным кольцами луком и ломтиками сыра",
      "duration": 60,
      "products": [
        {"name":  "лук", "amount":  20},
        {"name":  "сыр", "amount":  30}
      ]
    },
    {
      "name": "сбрызнуть маслом",
      "duration": 5,
      "products": [
        {"name": "оливковое масло", "amount": 2}
      ]
    },
    {
      "name": "посыпать орегано",
      "duration": 5,
      "products": [
        {"name": "орегано", "amount": 2}
      ]
    },
    {
      "name": "поставить в духовку",
      "duration": 1200,
      "products": []
    },
    {
      "name": "Порезать на 6 частей",
      "duration": 15,
      "products": []
    }
  ]
}


###
POST http://localhost:8080/item
Content-Type: application/json

{
  "name": "Золотая осень",
  "description": "Кабачки, Груши, Яблоки, Изюм, Лимон, Растительное масло, Сахар, Соль",
  "price": 229.0,
  "category": "Салат",
  "routeStages": [
    {
      "name": "Кабачки нарезать тонкими кружочками",
      "duration": 45,
      "products": [
        {"name": "Кабачки", "amount": 40}
      ]
    },
    {
      "name": "Груши и яблоки очистить от кожицы, вынуть сердцевину, нарезать и добавить к кабачкам",
      "duration": 60,
      "products": [
        {"name": "Груши", "amount": 40},
        {"name": "Яблоки", "amount": 40}
      ]
    },
    {
      "name": "Посыпать изюмом",
      "duration": 5,
      "products": [
        {"name": "Изюм", "amount": 20}
      ]
    },
    {
      "name": "добавить сахарный песок, соль",
      "duration": 8,
      "products": [
        {"name": "Сахар", "amount": 0.2},
        {"name": "Соль", "amount": 0.2}
      ]
    },
    {
      "name": "перемешать",
      "duration": 15,
      "products": []
    },
    {
      "name": "поставить в холодильник",
      "duration": 7200,
      "products": []
    },
    {
      "name": "полить растительным маслом",
      "duration": 5,
      "products": [
        {"name": "Растительное масло", "amount": 2}
      ]
    }
  ]
}


###
POST http://localhost:8080/item
Content-Type: application/json

{
  "name": "салат из белокочанной капусты по-румынски",
  "description": "Капуста, Морковь, Яблоки, Зеленый лук, Консервированная кукуруза, Сметана, Лимон, Сахар, Соль",
  "price": 209.0,
  "category": "Салат",
  "routeStages": [
    {
      "name": "Капусту, морковь и зеленый лук очистить, промыть и нашинковать",
      "duration": 120,
      "products": [
        {"name": "Свежая белокочанная капуста", "amount": 35.5},
        {"name": "Морковь", "amount": 12.5},
        {"name": "Зеленый лук", "amount": 5}
      ]
    },
    {
      "name": "Яблоки очистить, промыть, нарезать на дольки, удалив сердцевину, и также нашинковать",
      "duration": 60,
      "products": [
        {"name": "Яблоки", "amount": 40}
      ]
    },
    {
      "name": "Все соединить с консервированной кукурузой",
      "duration": 20,
      "products": [
        {"name": "Консервированная кукуруза", "amount": 20}
      ]
    },
    {
      "name": "Заправить лимоном, сахарным песком, солью и сметаной",
      "duration": 60,
      "products": [
        {"name": "Лимон", "amount": 0.05},
        {"name": "Сахар", "amount": 0.2},
        {"name": "Соль", "amount": 0.2},
        {"name": "Сметана", "amount": 15}
      ]
    }
  ]
}


###
POST http://localhost:8080/item
Content-Type: application/json

{
  "name": "Прага",
  "description": "Яблоки, Телятина, Свинина, Лук репчатый, Соленые огурцы, Растительное масло, Лимон, Соль, Майонез, Перец чёрный молотый",
  "price": 269.0,
  "category": "Салат",
  "routeStages": [
    {
      "name": "Телятину и свинину поджарить крупными кусками",
      "duration": 360,
      "products": [
        {"name": "Телятина", "amount": 40},
        {"name": "Свинина", "amount": 40}
      ]
    },
    {
      "name": "Жареное мясо, очищенные яблоки, соленые огурцы нарезать полосками, лук - тонкими полукольцами",
      "duration": 180,
      "products": [
        {"name": "Яблоки", "amount": 40},
        {"name": "Соленые огурцы", "amount": 12},
        {"name": "Лук репчатый", "amount": 10}
      ]
    },
    {
      "name": "Все соединить",
      "duration": 30,
      "products": []
    },
    {
      "name": "добавить лимонный сок, перец, соль",
      "duration": 60,
      "products": [
        {"name": "Лимон", "amount": 2},
        {"name": "Перец молотый черный", "amount": 0.1},
        {"name": "Соль", "amount": 0.1}
      ]
    },
    {
      "name": "заправить майонезом",
      "duration": 60,
      "products": [
        {"name": "Майонез", "amount": 10}
      ]
    }
  ]
}


###
POST http://localhost:8080/item
Content-Type: application/json

{
  "name": "закуска из сардин с овощами",
  "description": "Консервированные в масле сардины, Свежие помидоры, Свежие огурцы, Болгарский перец, Сыр, Яйцо, Лук репчатый, Растительное масло, Чеснок, Соль, 6% уксус, Тмин молотый, Перец чёрный молотый, Вода",
  "price": 229.0,
  "category": "Закуски",
  "routeStages": [
    {
      "name": "запечь помидоры, болгарский перец и очищенный лук в духовке",
      "duration": 7200,
      "products": [
        {"name": "Свежие помидоры", "amount": 17},
        {"name": "Болгарский перец", "amount": 10},
        {"name": "Лук", "amount": 10}
      ]
    },
    {
      "name": "очистить помидоры и перец от кожицы, удаляя из них семена",
      "duration": 100,
      "products": []
    },
    {
      "name": "нарезать мелко овощи",
      "duration": 60,
      "products": []
    },
    {
      "name": "перемешать",
      "duration": 30,
      "products": []
    },
    {
      "name": "добавляют соль, очищенный от кожицы и нарезанный кубиками огурец",
      "duration": 80,
      "products": [
        {"name": "Соль", "amount": 0.2},
        {"name": "Свежие огурцы", "amount": 15}
      ]
    },
    {
      "name": "полить смесью лимонного сока и 1 ст. ложки масла",
      "duration": 60,
      "products": [
        {"name": "Лимонный сок", "amount": 0.2},
        {"name": "Растительное масло", "amount": 2}
      ]
    },
    {
      "name": "добавить толченый чеснок, тмин, сыр, перец, измельченную рыбу и оставшееся масло",
      "duration": 80,
      "products": [
        {"name": "Чеснок", "amount": 0.2},
        {"name": "Тмин молотый", "amount": 0.2},
        {"name": "Сыр", "amount": 14},
        {"name": "Консервированные в масле сардины", "amount": 20}
      ]
    },
    {
      "name": "смешать",
      "duration": 20,
      "products": []
    }
  ]
}


###
POST http://localhost:8080/item
Content-Type: application/json

{
  "name": "Шопский",
  "description": "Свежие помидоры, Свежие огурцы, Болгарский перец, Лук репчатый, Брынза или сыр Фета, Растительное масло, 6% уксус, Соль, Перец чёрный молотый",
  "price": 269.0,
  "category": "Салат",
  "routeStages": [
    {
      "name": "Огурцы нарезать соломкой",
      "duration": 45,
      "products": [
        {"name": "Огурцы", "amount": 27}
      ]
    },
    {
      "name": "Помидоры нарезать кубиками",
      "duration": 45,
      "products": [
        {"name": "Помидоры", "amount": 30}
      ]
    },
    {
      "name": "Перец очистить от семян, нарезать соломкой",
      "duration": 60,
      "products": [
        {"name": "Перец болгарский", "amount": 30}
      ]
    },
    {
      "name": "Лук нарезать соломкой",
      "duration": 45,
      "products": [
        {"name": "Лук репчатый", "amount": 10}
      ]
    },
    {
      "name": "Смешать огурцы, помидоры, перец, лук",
      "duration": 30,
      "products": []
    },
    {
      "name": "Добавить брынзу",
      "duration": 30,
      "products": [
        {"name": "Брынза", "amount": 14}
      ]
    },
    {
      "name": "Для заправки смешать масло и уксус",
      "duration": 45,
      "products": [
        {"name": "Растительное масло", "amount": 2},
        {"name": "Уксус", "amount": 1.3}
      ]
    },
    {
      "name": "Поперчить, немного посолить (можно не солить совсем, брынза довольно соленая)",
      "duration": 45,
      "products": [
        {"name": "Майонез", "amount": 10}
      ]
    },
    {
      "name": "Все перемешать",
      "duration": 60,
      "products": []
    }
  ]
}
