###
GET http://localhost:8080/items
Content-Type: application/json

###
GET http://localhost:8080/item/sdfsadf
Content-Type: application/json

###
GET http://localhost:8080/find/гурцы нарезать солом
Content-Type: application/json

###
POST http://localhost:8080/publish
Content-Type: application/json

[
  "73deec2f-627a-4f0a-a17f-afc9ee8cfede"
]

###
GET http://localhost:8081/menu
Content-Type: application/json

###
POST http://localhost:8081/carts
Content-Type: application/json

{
  "item_id": "<item_id>",
  "amount": 2
}

###
PUT http://localhost:8081/carts
Content-Type: application/json

{
  "item_id": "<item_id>",
  "amount": 10
}

###
PUT http://localhost:8081/carts
Content-Type: application/json

{
  "item_id": "<item_id>",
  "amount": 0
}

###
GET http://localhost:8081/carts/<cart_id>
Content-Type: application/json

###
DELETE http://localhost:8081/carts/<cart_id>
Content-Type: application/json

###
DELETE http://localhost:8081/carts/<cart_id>/items/<item_id>
Content-Type: application/json

###
GET http://localhost:8081/carts/<cart_id>/pay
Content-Type: application/json
