###
GET http://localhost:8080/items
Content-Type: application/json

###
GET http://localhost:8080/item/sdfsadf
Content-Type: application/json

###
GET http://localhost:8080/find/гурцы нарезать солом
Content-Type: application/json

###
POST http://localhost:8080/publish
Content-Type: application/json

[
  "63f8b0b5-659d-48ea-968a-7b8a0eb15077",
  "392e3254-b730-437e-899b-bcaf4b396fe0"
]

###
GET http://localhost:8081/menu
Content-Type: application/json

###
POST http://localhost:8081/carts
Content-Type: application/json

{
  "itemId": "63f8b0b5-659d-48ea-968a-7b8a0eb15077",
  "amount": 2
}

###
POST http://localhost:8081/carts
Content-Type: application/json

{
  "cartId": "0dd5e063-4a03-4a30-b975-884456c63554",
  "itemId": "392e3254-b730-437e-899b-bcaf4b396fe0",
  "amount": 1
}

###
PUT http://localhost:8081/carts
Content-Type: application/json

{
  "cartId": "0dd5e063-4a03-4a30-b975-884456c63554",
  "itemId": "63f8b0b5-659d-48ea-968a-7b8a0eb15077",
  "amount": 10
}

###
PUT http://localhost:8081/carts
Content-Type: application/json

{
  "cartId": "0dd5e063-4a03-4a30-b975-884456c63554",
  "itemId": "63f8b0b5-659d-48ea-968a-7b8a0eb15077",
  "amount": 0
}

###
GET http://localhost:8081/carts/0dd5e063-4a03-4a30-b975-884456c63554
Content-Type: application/json

###
DELETE http://localhost:8081/carts/0dd5e063-4a03-4a30-b975-884456c63554
Content-Type: application/json

###
DELETE http://localhost:8081/carts/0dd5e063-4a03-4a30-b975-884456c63554/items/63f8b0b5-659d-48ea-968a-7b8a0eb15077
Content-Type: application/json

###
GET http://localhost:8081/carts/0dd5e063-4a03-4a30-b975-884456c63554/pay
Content-Type: application/json
